title: threeC.tv - Blog
author: Adam1901
email: adam@threec.tv
description: > # this means to ignore newlines until "baseurl:"
  A community focused streaming platform. Focusing on growing and joining communities

# social links
twitter_username: threeCTV # DO NOT include the @ character, or else the build will fail!
github_username:  threec-tv # DO NOT include the @ character, or else the build will fail!

theme: jekyll-theme-slate
encoding: UTF-8